name: CMake

on:
  push:
    branches: [ "main" ]

env:
  build_directory: ${{github.workspace}}/BUILD
  build_type: Release
  release_name: build_${{github.run_number}}

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04]
        platform: [32, 64]
        exclude:
          - os: ubuntu-22.04
            platform: 32
        
    runs-on: ${{matrix.os}}

    steps:
    - name: Customize Software
      run: |
        sudo snap install cmake --classic
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: CMake Configure (win32)
      if: ${{ matrix.os == 'windows-2022' && matrix.platform == 32 }}
      run: cmake -B ${{env.build_directory}} -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=${{env.build_type}} -DREDUMPER_VERSION_BUILD=${{github.run_number}}

    - name: CMake Configure (win64)
      if: ${{ matrix.os == 'windows-2022' && matrix.platform == 64 }}
      run: cmake -B ${{env.build_directory}} -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.build_type}} -DREDUMPER_VERSION_BUILD=${{github.run_number}}

    - name: CMake Configure (linux64)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: cmake -B ${{env.build_directory}} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.build_type}} -DREDUMPER_VERSION_BUILD=${{github.run_number}}

    - name: CMake Build
      run: cmake --build ${{env.build_directory}} --config ${{env.build_type}}
      
    - name: CTest
      working-directory: ${{env.build_directory}}
      run: ctest -C ${{env.build_type}}

    - name: CPack
      working-directory: ${{env.build_directory}}
      run: cpack -G ZIP --config CPackConfig.cmake

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.release_name}}
        path: ${{env.build_directory}}/redumper-*.zip
        
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{env.release_name}}
      
      - name: 'Create Release'
        shell: bash
        run: |
          for f in redumper-*.zip; do FILES+=" -a $f"; done
          hub release create ${{ env.release_name }} -m ${{ env.release_name }} $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
